In [9]:
class student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"my name is {self.name}, age is {self.age}"

    def __repr__(self) -> str:
        return f"my name is {self.name}, age is {self.age}"

In [11]:
s1 = student("test", 10)
str(s1)
s1

my name is test, age is 10

In [12]:
import numpy as np

In [15]:
s = np.array(5)
print(s.ndim)
print(s.shape)

print("========")
 
v = np.array([1,2,3,4,5,6])
print(v.ndim)
print(v.shape)

print("========")
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m.ndim)
print(m.shape)


0
()
1
(6,)
2
(3, 3)


In [19]:
vec=np.array([1,2,3,4,5,6])
mat=vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec=np.array([1,2,3,4])
mat=vec.reshape((vec.shape[0],1))//get no. of rows
mat

array([[1],
       [2],
       [3],
       [4]])

In [24]:
vec=np.array([1,2,3,4])
vec[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [25]:
def arr_reshape(arr:list ,rows:int , cols:int ):
    try:
        arr=np.array(arr)
        return arr.reshape(rows,cols)
    except(TypeError, ValueError) as e:
        raise ValueError(f"invalid reshape operation :{e}")
    

In [30]:
vec=[1,2,3,4,5,6]
arr_reshape(vec, 2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
class c:
    x=3
o1=c()
mat=np.array([[1, 2],
             [1, 4],
            [o1, 6]])
print(mat.dtype)
print(mat)

object
[[1 2]
 [1 4]
 [<__main__.c object at 0x000002DFD2B759A0> 6]]


In [55]:
mat=np.array([[1, 2],
             [1, 4],
            ['6', 6]])
fmat=mat.astype(float)
print(fmat.dtype)
fmat

float64


array([[1., 2.],
       [1., 4.],
       [6., 6.]])

In [68]:
mat=np.array([[1, 2],
             [1, 4],
            [5, 6]])
vec=np.array([2,3,5,1])
mat[1:3, 0:2]

array([[1, 4],
       [5, 6]])

In [71]:
m=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matt=m.T
matt

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
mat=np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
mat=np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
mat=np.full((3,4),4)
mat

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])